### ISSUE TITLE
Proper way to do Randomized QMC

### ISSUE THREAD

**Issue by dmetivie** [QMCSoftware/QMCSoftware#282]
I had the same question for the [SciPy QMC](https://github.com/scipy/scipy/issues/15398) and just wanted to check that it was working similarly for QMCPy.
As I did not find that in the docs, I post that here (maybe adding a comment in the doc would be helpful?).

My question:
If my goal is to generate `M` independent copies of a randomized LD sequence of a fixed given size `N` (Sobol, Lattice, Halton, ...).
I should do
```
import qmcpy as qmc
import numpy as np

N = 2**16
M = 10
d = 10
```
```
# Option 1
sample = np.zeros((M,N,d))
for i in range(0,M):
    sampler = qmc.DigitalNetB2(dimension=d) # or qmc.Lattice or qmc.Halton
    sample[i,:,: ] = sampler.gen_samples(N)
```
I should NOT do
```
# Option 2
sampler = qmc.DigitalNetB2(dimension=d) # or qmc.Lattice or qmc.Halton
for i in range(0,M):
    sample[i,:,: ] = sampler.gen_samples(N)
```
which is much faster because it generates the sampler only once. 
BUT if I understand correctly the way the SciPy version work (and assume this one does work the same) this Option 2 version generates the number of the sequence `N+1,...,2N` then `2N+1,...,3N` which (at least for Sobol) is not wanted (because we lose the digital net property).

If that is the case and option 1 is the proper way to have the first `N` randomized `M` times, is there a way to do that faster (I guess some calls inside the sampler could be avoided)?

**Comment by alegresor** [comment]
Hi @dmetivie, thank you for submitting this issue.

The best way to generate independent randomizations of a low discrepancy sequence in QMCPy is to do 

```python
import qmcpy
import numpy 

s,n,d = 3,4,2
samples = numpy.zeros((s,n,d),dtype=float)
dnb2 = qmcpy.DigitalNetB2(d)
dnb2s = dnb2.spawn(s=s)
for i in range(s):
    samples[i] = dnb2s[i].gen_samples(n_min=0, n_max=n)
print(samples)
```

The syntax is the same for other low discrepancy sequences.  

The `dnb2.spawn(s=s)` line creates `s` copies of the current `DigitalNetB2` instance but with independent randomizations. This is similar to doing something like 

```python
dnb2s = [qmcpy.DigitalNetB2(d, seed=i) for i in range(1,s+1)]
```

except the seeds are chosen by an underlying [`numpy.SeedSequence`](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.SeedSequence.html) to create bit generators with "better independence".

Note that in QMCPy calling `gen_samples(n)` on a low discrepancy sequence produces elements from index 0 (`n_min`) to index `n` (`n_max`, not inclusive), even on repeated calls. So your code for

```python
# Option 2
sampler = qmc.DigitalNetB2(dimension=d) # or qmc.Lattice or qmc.Halton
for i in range(0,M):
    sample[i,:,: ] = sampler.gen_samples(N)
```

will make `sample[i]` the same for all `i`. 

As for generating a base sequence and then applying independent randomizations without regenerating the base sequence: this is not yet supported in QMCPy. By default, `DigialNetB2` uses a combined linear matrix scrambling and digital shift randomization.  The linear matrix scrambling modifies the underlying generating matrices, so `DigitalNetB2` instances with different seeds will have different base sequences and regenerating is unavoidable. If you only apply a digital shift (and not a linear matrix scramble), then this is possible, but not yet supported.

Support for this is straightforward, but requires modifying the underlying C generator since the shift is applied to the base sequence bits before being converted to floats. Supporting this would also be difficult for the `Halton` generator and would probably be easiest for the `Lattice` generator since everything is in Python and randomization is a one-liner.

**Comment by dmetivie** [comment]
Many thanks for the clarifications!

**Comment by alegresor** [comment]
@dmetivie 

The below code generates independent randomizations of a base lattice sequence

```python
import qmcpy
import numpy 
s,n,d = 3,4,2
lattice = qmcpy.Lattice(d, randomize=False)
x = lattice.gen_samples(n, warn=False)
xs = numpy.tile(x, reps=(s,1,1))
for r in range(s):
    xs[r] = (xs[r]+numpy.random.rand(d))%1
print(xs)
```

and outputs

```
[[[0.89134961 0.46782937]
  [0.39134961 0.96782937]
  [0.14134961 0.21782937]
  [0.64134961 0.71782937]]

 [[0.14521141 0.67683425]
  [0.64521141 0.17683425]
  [0.39521141 0.42683425]
  [0.89521141 0.92683425]]

 [[0.21430444 0.6717996 ]
  [0.71430444 0.1717996 ]
  [0.46430444 0.4217996 ]
  [0.96430444 0.9217996 ]]]
```
