### ISSUE TITLE
Speed up code with parallelization, GPU, other? 

### ISSUE THREAD

**Issue by lmatar** [QMCSoftware/QMCSoftware#59]

**Comment by alegresor** [comment]
Possible softwares
- [Parsl](https://parsl-project.org/) and [Numba](http://numba.pydata.org/) for parallel computing
- PyTorch for GPU computation

**Comment by alegresor** [comment]
`Integrand` supports a `parallel` option that seamlessly uses multiprocessing on a specified number of cores whenever the function is to be evaluated. For example
```python
def myfun(t): return t.sum(1)
if __name__ == '__main__':
    from qmcpy import *
    cf = CustomFun(Gaussian(DigitalNetB2(3)),myfun,parallel=4)
    x = cf.discrete_distrib.gen_samples(4*2**8)
    y = cf.f(x)
    print(y.mean())
```
uses 4 cores to evaluate 4*2^8 points by evaluating 2^8 points on each core. 

I think this sort of parallelism provides the most bang for one's buck because evaluating the user's function is likely to be the bottleneck since QMCPy's algorithms are already fast and backed by NumPy C-backed routines. 

Other developers are working at different parallelism angles. Check other issues for more recent parallelism developments in QMCPy!
